config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "dashboard", to: "dashboard#index"

  resources :pets do
    # Booking is displayed on /pets/:id/bookings/new
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :edit, :update]

  resources :pages
  resources :users
  get "profile", to: "users#profile"

  get "about_us", to: "pages#about_us", as: :about

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :pet

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :period_must_be_during_availability

  def period_must_be_during_availability
    return unless start_date.present? && end_date.present?

    unless pet.available?(start_date, end_date)
      # the booking is not valid
      # since this is not related to a column in particular but to the
      # booking as a whole, we add an error to `:base`, i.e. the booking object
      # see: https://guides.rubyonrails.org/active_record_validations.html#errors-base
      errors.add(:base, :invalid, message: "The pet is not available")
    end
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :bookings

  has_many :availabilities
  belongs_to :user
  has_one_attached :image


  validates :name, presence: true
  validates :breed, presence: true
  validates :image, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def available?(start_date, end_date)
    Availability
      .where(pet: self)
      .where("start_date <= :start_date AND end_date >= :end_date", { start_date: start_date, end_date: end_date })
      .exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets
  has_many :bookings

  validates :username, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
require 'time'

class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update]

  def index
    @bookings = current_user.bookings
  end

  def new
    @pet = Pet.find(params[:pet_id])
    @booking = Booking.new
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @booking = @pet.bookings.build(booking_params.merge(user: current_user))
    # @booking.user = current_user
    if @booking.save
      redirect_to @pet, notice: 'Booking was successfully created.'
    else
      render "pets/show", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to bookings_path, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :booking_note)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookings = current_user.bookings
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # Add a new button here. link
    @pets = Pet.all
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

##MapBox
def index
  @pets = Pet.all
  @pets = @pets.where(user_id: params[:user_id]) if params[:user_id]
  # The `geocoded` scope filters only flats with coordinates
  @markers = @pets.geocoded.map do |pet|
    {
      lat: pet.latitude,
      lng: pet.longitude
    }
  end
end

  def show
    @pet = Pet.find(params[:id])
    @booking = Booking.new
  end

  def new
    @pet = Pet.new
  end

  def create
    # @pet = Pet.new(pet_params)
    # @pet.user = current_user
    @pet = current_user.pets.build(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy! if current_user == @pet.user
    redirect_to pets_path
  end


#MapBox

  private

  def pet_params
    params.require(:pet).permit(:name, :breed, :description, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # This is a comment
    def profile
        @user = current_user
        @bookings = @user.bookings
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Hello from edit Bookings</h1>


<%= simple_form_for @booking do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :booking_note %>
  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <h1>Bookings List</h1>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Booking Note</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.start_date.day%>/<%= booking.start_date.month%>/<%= booking.start_date.year%></td>
          <td><%= booking.end_date.day%>/<%= booking.end_date.month%>/<%= booking.end_date.year%></td>
          <td><%= booking.booking_note %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Back to homepage", root_path %>
</div>

app/views/dashboard/index.html.erb
<h1>My page</h1>

<% @bookings.each do |booking| %>
  <h3>Owner</h3>
  <%= booking.pet.user %>
  <h3>Pet</h3>
  <%= booking.pet %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Perfect Fur Hire</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chicle&display=swap" rel="stylesheet">

    <%# MAPBox Api %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%# End of MapBox %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
  
</html>

app/views/pages/about_us.html.erb
<div class="container">
<br>
    <h2>About Perfect Fur Hire </h2>
    <br>
    <p>Welcome to our website! About Rover
        Welcome to the world's largest network of 5-star pet sitters and dog walkers.
        We believe everyone deserves the unconditional love of a pet - and at Rover, our mission is to make it easier to experience that love.

        Founded in 2011, the Rover app and website connect dog and cat parents with loving pet sitters and dog walkers in neighborhoods across the US, Canada, the UK and Europe.

        We empower our community of trusted pet sitters and dog walkers to run their own pet care services on Rover with the tools and security of a global company to back them </p>
    <br>
    <br>

    <p>   Millions of services booked. Thousands of wagging tails.10 countries 24,000 + neighbourhoods around the world 2+ million
    pet owners have booked pet care through Rover Millions of 5-star reviews from pet owners.</p>
  <!-- Add more content as needed --> 
    <br>

    
</div>
    <%= image_tag "pets.png", class: 'img-about-us w-100'%> 

<br>
<div class="container">
    <p>  Good pets. Good people.
        Whether you need a dog walker for the day, overnight boarding for a month, or daily visits for your cat, there's a sitter on Rover who's the perfect match for you, your pets and your lifestyle. Sitters on Rover offer:  </p>
    <div class="row">
        <div class="col-sm-6">
            <ul class="about-us-content__list">
                <li>Boarding</li>
                <li>Pet Sitting</li>
                <li>Dog Walking</li>
            </ul>
        </div>
        <div class="col-sm-6">
            <ul class="about-us-content__list">
                <li>Doggy Day Care</li>
                <li>Drop-in Visits</li>
                <li>House Sitting</li>
            </ul>
        </div>
    </div>
 <%# <img src="yusuf62.png" alt="Description of the image"> %>

  <!-- Add more content as needed -->
</div>

 <%= image_tag "petts.png", class: 'img-about-us w-100'%>

app/views/pages/home.html.erb
<%#
<div class="home-page">
  <video autoplay loop muted  class= "w-100">
    <source src="<%= asset_path 'yusuf.mp4' " type="video/mp4">
    Your browser does not support the video tag.
  </video>

  <audio controls autoplay style="float:right; margin: 1rem;">
    <source src="<%= asset_path("jane.mp3") " type="audio/mpeg">
    Your browser does not support the audio element.
  </audio>

  <h2 class="brand-name">Perfect fur Hire</h2>
  <a class="btn btn-ghost" href="#">View all pets</a>
  <%# <%= link_to "View all pets", pets_path, class: "btn btn-ghost"

</div> %>


<%# newuser = User.create( email: "ai@miyuki.ai", password: "password123", password_confirmation: "password123" ) %>


<video autoplay loop muted  class= "w-100">
    <source src="<%= asset_path 'yusuf.mp4' %>" type="video/mp4">
    Your browser does not support the video tag.
</video>

<div class="container d-flex justify-content-center">
  <header class="viewport-header">
    <h2 class="brand-name">Perfect fur Hire</h2>
    <div class="home-cta">
      <%= link_to "Browse pets", pets_path, class: "btn btn-ghost cta-link" %>
    </div>
    <audio controls autoplay style="float:right; margin-top: 1rem; width: 250px;" id="audio-landing">
      <source src="<%= asset_path("jane.mp3") %>" type="audio/mpeg" >
      <%# Your browser does not support the audio element. %>
    </audio>
  </header>
</div>


<%# <a class="btn btn-ghost" href="#">View all pets</a> %>

app/views/pets/index.html.erb
<div class="container">

  <div class="row">

    <div  id="dog-container" class="col-sm-8">
      <h1>List of pets</h1>
      <%# -------START----CARDS------ %>
      <%# <div class="cards"> %>
      <div class="d-flex flex-row flex-wrap">
        <% @pets.each do |pet| %>
          <div class="card m-2" style="width: 200px;" ><%# ------size--CARDS--------- %>
            <%= image_tag pet.image, class: "card-img-top", style: "width: auto; height:auto; object-fit: cover; border-radius: 3%;" %>
            <div class="card-body">
              <h5 class="card-title"><%= pet.name %></h5>
              <p class="card-text" style="font-size: x-small;"><%= pet.description %></p>
              <%= link_to "Book >", pet, class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>

      </div>
    </div>

    <%# ------END--CARDS--------- %>

    <%# -------MAP-------- %>
    <div id="map" class="col-sm-4 position-sticky sticky-top">
      <div style="width: auto; height: 100vh;"

        data-controller="map"

        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <%# -------END---MAP-------- %>
  </div>
</div>
  <%# -------main container DIV-------- %>

app/views/pets/new.html.erb
<div class="container mt-5">

  <h1>Add a pet</h1>
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name %>
    <%= f.input :breed %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.button :submit, class: "btn btn-outline-dark" %>
  <% end %>

</div>

app/views/pets/show.html.erb
<div class="container d-flex flex-column">
  <h1 class="my-3">Meet <%= @pet.name %></h1>
  <div class="col-8 d-flex align-self-center">
    <div class="col-6 mx-5">
      <%= image_tag @pet.image, class: "rounded align-self-center card-img-top", style: "width: 280px;" %>
      <div class="card-body">
        <p class="card-text my-4"><%= @pet.description %></p>
      </div>
    </div>

    <div class="col-6" data-controller="pets">
      <%= render "shared/form", booking: @booking %>
      <% if current_user == @pet.user %>
        <%= link_to "Delete", pet_path(@pet), class: "btn btn-outline-dark my-5", "data-turbo-method" => :delete %>
      <% end %>
      <%= link_to "Return to pets", pets_path, class: "btn btn-outline-dark my-4" %>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<% if @pet.availabilities.count > 0 %>
  <script>
    window.petAvailabilities = <%= @pet.availabilities.to_json.html_safe %>;
    window.petBookings = <%= @pet.bookings.to_json.html_safe %>;
  </script>

  <div data-controller="datepicker">
    <%= simple_form_for [@pet, @booking] do |f| %>
      <%= f.input :start_date, as: :hidden, input_html: { "data-datepicker-target" => "start" } %>
      <%= f.input :end_date, as: :hidden, input_html: { "data-datepicker-target" => "end" } %>

      <div data-datepicker-target="calendar"></div>
      <% if user_signed_in? %>
        <div class="my-3">
          <%= f.input :booking_note %>
        </div>
        <%= f.error :base, class: "text-danger" %>
        <%= f.submit %>
      <% else %>
        <p>Plese <%= link_to "login", new_user_session_path %> to book a pet</p>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p>Apologies but <%= @pet.name %> is currently unavailable</p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Perfect fur hire", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="nav justify-content-end">
      <!-- user_signed_in? returns true only if there is a user currently logged in -->
      <!-- this is a helper provided by devise -->
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add a pet", new_pet_path, class: "nav-link link-light" %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link link-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", bookings_path, class: "nav-link link-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Pets", pets_path(user_id: current_user), class: "nav-link link-light" %>
          </li>
        <% else %>
          <li class="nav-item active d-flex">
            <%= link_to "About Us", about_path, class: "nav-link btn btn-outline-home" %>   <!-- Adding the new "home" button -->
            <%= link_to "Signup", new_user_registration_path, class: "nav-link btn btn-outline-success" %>
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-outline-success" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/profile.html.erb
<h1> hello lovely people </h1>